server:
  port: 1001

spring:
  application:
    name: provider1-service

eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
      defaultZone: http://localhost:8000/eureka
      ###需要将服务注册到eureka上
    register-with-eureka: true
    #####需要去检索服务信息
    fetch-registry: true
