server:
  port: 8801

eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
      defaultZone: http://127.0.0.1:8761/eureka
      ###需要将服务注册到eureka上
    register-with-eureka: true
    #####需要去检索服务信息
    fetch-registry: false

spring:
  application:
    name: provider-fein

hystrix:
  metrics:
    enabled: true
