##spring.redis.cluster.nodes=192.168.131.131:6379,192.168.131.131:6380
##spring.redis.cluster.timeout=2000
##spring.redis.cluster.max-redirects=8
#
#spring.redis.host=192.168.131.131
#spring.redis.port=6379
## 登录redis服务器的密码。
#spring.redis.password=
## 启用SSL支持。
#spring.redis.ssl=false
## 池在给定时间可以分配的最大连接数。使用负值无限制。
#spring.redis.jedis.pool.max-active=8
#spring.redis.jedis.pool.max-idle=8
## 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
#spring.redis.jedis.ppool.max-wait=-1
## 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
#spring.redis.jedis.ppool.min-idle=0
## （哨兵模式，不使用则不用开启）Redis服务器的名称。
## spring.redis.sentinel.master=
## （哨兵模式，不使用则不用开启）主机：端口对的逗号分隔列表。
## spring.redis.sentinel.nodes=
#spring.redis.timeout=2000

spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_CORE:0}
    timeout: 2000