server:
  port: 8080
  servlet:
    context-path: /alan
  tomcat:
    max-http-post-size: -1
  max-http-header-size: -1

# spring actuator
info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    test: test

logging:
  config: classpath:logback-spring.xml