#server:
#  port: 8080
config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长，豪秒
    expire: 8000
    # header 名称
    header: token
#spring:
#  application:
#    name: jwt

#  设置tomcat Header 传输字节大小
server:
  max-http-header-size: 102400
#
