server:
  port: 8010

spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
      defaultZone: http://eureka-server:8761/eureka/,http://eureka-server:8762/eureka/
  instance:
    hostname: consumerName

