spring:
  application:
    name: user-consumer

server:
  port: 9003

# 与服务端一致
eureka:
  server:
    ip: 192.168.23.15:8761

  client:
    #####需要去检索服务信息
    fetch-registry: false
    #需要将服务注册到eureka上
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.server.ip}/eureka/

feign:
  hystrix:
    enabled: false

# 开启DEBUG模式
logging:
  level:
    root: info

