server:
  port: 9999


eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: consumer-feign
  main:
    allow-bean-definition-overriding: true

  #zipkin 链路监控 相关
  zipkin:
    base-url: http://192.168.176.131:9411/
    #配置百分比导出，这里是100%
    annotation:
      enabled: true
  #springboot1.x与2.x是有区别的
  sleuth:
    sampler:
      probability: 1

logging:
  level:
    org.springframework.cloud: debug
#必须开启，否则报Load balancer does not have available server for client异常
ribbon:
  eureka:
    enabled: true
