server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:8762/eureka/
    ###因为自己是注册中心，是否需要将自己注册给自己（集群时是需要为 true)
    register-with-eureka: false
    # 不检索服务
    fetch-registry: false

  server:
    #线上的时候 一定要去除，目的是不使用cloud的安全策略
    enable-self-preservation: false

spring:
  application:
    name: eureka-server1
