server:
  port: 8888



spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:58.87.88.74}:${DB_PORT:3306}/${DB_NAME:gps_training}?autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Zhuoyuew@killhacker*94@}
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.aidoctor.decisiontree.po.*
  mapper-locations: classpath:mybatis/*.xml

logging:
  level:
    root: info
    com.aidoctor: debug
